### PR TITLE
Create Quickstart Guide for absolute newbies

### PR DESCRIPTION
**Pull request by anjchang**
A friend asked me how they would use your project. They had no idea how to run it, and so I wrote an email describing the steps needed to get it running. Hope this is helpful. --anjchang

### CODE REVIEW

**Comment by neauoire** [comment]
They should get Binaries from https://hundredrabbits.itch.io/marabu

**Comment by neauoire** [comment]
But thanks for the build guide, I will keep it 👍

**Comment by anjchang** [comment]
Thanks! I'll pass that on to my friend. Happy Holidays!

**Comment by anjchang** [comment]
He said that compiling it worked for him, because the initial download of just the binaries quit working. His exact email to me:
"Hey thanks Angela! I downloaded the Mac binary and installed it, and initially it worked but now I can't get it to produce sound.

However, I followed the instructions in your last message about installing npm and installing from there and it worked perfectly -"  In any case. Thanks for including the newbie guide. Happy Holidays! Anj

**Comment by anjchang** [comment]
Wishing you well on your sailing journey, btw!

**Comment by neauoire** [comment]
Ah! Well that's not good that it's not working for him. I'll investigate :)
I'm glad compiling binaries work tho :)

Cheers!

**Pull request merged**
